### ISSUE TITLE
StreamManager dependency requirements

### ISSUE THREAD

**Issue by Callumjn** [aws-greengrass/aws-greengrass-stream-manager-sdk-java#1]
Hi,

When making use of greengrass stream manager in a custom GreenGrassV2 component including the dependencies listed in the example build.gradle file in a custom component POM file;

```
dependencies {  
    compile 'com.fasterxml.jackson.core:jackson-core:2.8.8'  
    compile 'com.fasterxml.jackson.core:jackson-databind:2.8.8'  
    compile 'org.apache.httpcomponents:httpclient:4.5.3'  
    compile 'com.amazonaws:aws-lambda-java-core:1.1.0'  
    compile 'com.amazonaws:aws-java-sdk-core:1.11.178'  
    compile fileTree(dir: 'libs', include: ['*.jar'])  
} 
```

I've found that you encounter a number of exceptions such as NoSuchMethodError and NoSuchFieldError upon attempting to run the custom component. From testing it appears that the following needs to be included as dependencies in the POM;

```
com.fasterxml.jackson.core
com.fasterxml.jackson.databind
com.fasterxml.jackson.annotation
com.fasterxml.jackson.dataformat
```

and that the version being used needs to be greater than 2.9. 

Is it possible to get the example build.gradle updated in the README for some additional clarity on what dependencies & versions are required when including the Stream Manager SDK in other components. Thanks!

**Comment by MikeDombo** [comment]
At this time all of the dependencies including Jackson are already included inside the jar which is uploaded here. It should not be necessary for you to add more dependencies.

**Comment by sushantAtAws** [comment]
Since this issue was created, we have released another version of the sdk jar `aws-greengrass-stream-manager-sdk-java-slim.jar` which does not have the dependencies built into the jar and the readme has been updated with the instructions. I would recommend giving that a try. Thanks
