### ISSUE TITLE
Updates and sources

### ISSUE THREAD

**Issue by tomikpik** [aws-greengrass/aws-greengrass-stream-manager-sdk-java#3]
Hi there,

I hope you're doing well. We're using this SDK in our production setup and find it incredibly useful. We noticed that the Python SDK has its source code available, and we were wondering if the Java SDK source code could be made available as well.

Having access to the source code would greatly assist us in customizing the SDK to better fit our needs. It would also provide transparency and encourage community collaboration.

We appreciate your hard work on the SDK and would be grateful for your consideration of this request.

Thanks,
Tom

**Comment by MikeDombo** [comment]
Hello Tomas,

Thank you for bringing this up. At this time we are not able to make the SDK properly open source. However, all Java is effectively open source as you can always decompile the jar for example by using [vineflower](https://github.com/Vineflower/vineflower?tab=readme-ov-file#use).

Open sourcing everything is on our list to do but I cannot provide you with any timeline.

**Comment by tomikpik** [comment]
Hi Mike, 
although I was hoping that you'd release the sources, this should work as well. I'll give it a try :)
Thanks
